### PR TITLE
Starter html

### PR DESCRIPTION
**Pull request by doebelc**
This is for the main page

### CODE REVIEW

**Comment by doebelc** [comment]
you were able to find the files?

**Comment by bjaegerthomas** [comment]
No, not yet, I think I just confirmed a readme that then merged into the
main.




http://jaegerthomas.com/
https://www.imdb.com/name/nm7161241

**Comment by doebelc** [comment]
Yea I saw that and I think I know what I did wrong with the background
image, we have any idea what we’re trying to work on today?

**Comment by bjaegerthomas** [comment]
I’m messing around with some JavaScript functions and am going to create a
branch to submit to the main for approval. Will do some more with it
tomorrow as well.


http://jaegerthomas.com/
https://www.imdb.com/name/nm7161241

**Comment by doebelc** [comment]
Ok I’ll see if I can add some type of chart for the middle of the main page

**Comment by bjaegerthomas** [comment]
Right on


http://jaegerthomas.com/
https://www.imdb.com/name/nm7161241

**Pull request merged**
